### PR TITLE
Replace Python 2 updater with OneUpdater

### PR DESCRIPTION
**Pull request by vitorgalvao**
Closes https://github.com/sballin/alfred-search-notes-app/issues/55.

[OneUpdater](https://www.alfredforum.com/topic/9224-oneupdater-—-update-workflows-with-a-single-node/) is a language-agnostic way to add auto-updating to Workflows. It uses bash and has been working reliably since 2016. I use it in all Workflows I distribute and it’s being used by several other authors as well.

If you prefer to set it up yourself instead of accepting the PR, it’s pretty easy to do so and the previously linked post explains it. The correct configuration for it is:

```shell
readonly remote_info_plist='https://raw.githubusercontent.com/sballin/alfred-search-notes-app/master/info.plist'
readonly workflow_url='sballin/alfred-search-notes-app'
readonly download_type='github_release'
readonly frequency_check='4'
```

This is “set it and forget it”. Keep the `info.plist` of this repo where it is and keep updating the Workflow’s version, and it’ll do everything else.

### CODE REVIEW

**Comment by arrelid** [comment]
Did a clean install of macOS Ventura today and ran into the /usr/bin/python2 invocation in the updater. Can't speak for this fix in itself, but would obviously like for a vanilla workflow installation to not rely on python2 any longer.

**Comment by vitorgalvao** [comment]
> Can't speak for this fix in itself

If it eases your mind, I’m a member of the Alfred team ([see the official org on GitHub for confirmation](https://github.com/orgs/alfredapp/people)) and the author of the update code itself, which is also included in official workflows and plenty of third-party ones. It’s battle-tested.

**Comment by aleksfadini** [comment]
> Did a clean install of macOS Ventura today and ran into the /usr/bin/python2 invocation in the updater. Can't speak for this fix in itself, but would obviously like for a vanilla workflow installation to not rely on python2 any longer.

I'm getting python 2 errors with this workflow (here: https://github.com/sballin/alfred-search-notes-app/issues/71 ). This workflow is amazing, one of my most used, but hasnt been updated in 2 years. Can we get a version that does not rely on python 2, which is deprecated now?

**Comment by sballin** [comment]
Sorry for the long wait, and thank you for the very helpful pull request! The latest version now uses OneUpdater: https://github.com/sballin/alfred-search-notes-app/releases/download/3.6/Search.Notes.alfredworkflow

**Pull request closed without merging**
